<?php
// ------------------------------------------------------------------------ //
// Xoops - PHP Content Management System                      			//
// Copyright (c) 2007 Xoops                           				//
// //
// Authors: 																//
// John Neill ( AKA Catzwolf )                                     			//
// Raimondas Rimkevicius ( AKA Mekdrop )									//
// //
// URL: http:www.Xoops.com 												//
// Project: Xoops Project                                               //
// -------------------------------------------------------------------------//
$modversion['name']                = _MI_WFCHANNEL_CHANNEL;
$modversion['version']             = 2.07;
$modversion['requires']            = 1.06;
$modversion['description']         = _MI_WFCHANNEL_CHANNELDESC;
$modversion['releasedate']         = 'Thursday 13.5.2010';
$modversion['author']              = 'John Neill';
$modversion['credits']             = 'I would like to thank all the people who in some way or another who have either helped with coding or contributed with the development of this module. Mark Boyden, many thanks for your contribution and help with the development of this module..and you may get your wish yet! ;)';
$modversion['status']              = '2.06 Beta';
$modversion['lead']                = 'John Neill aka Catzwolf';
$modversion['contributors']        = 'Predator, Phppp, Bender, giba and many others. Thank you :)';
$modversion['website_url']         = 'http://www.xoops.org';
$modversion['website_name']        = 'XOOPS Modules';
$modversion['email']               = 'support@xoops.org';
$modversion['demo_site_url']       = '';
$modversion['demo_site_name']      = 'WF-Channel Demo';
$modversion['support_site_url']    = 'http://xoops.org/forum/index.php';
$modversion['support_site_name']   = 'Offical Support Website';
$modversion['submit_bug_url']      = 'http://code.google.com/p/xoosla-modules/issues/list';
$modversion['submit_bug_name']     = 'Bug Submission';
$modversion['submit_feature_url']  = 'http://xoops.org/forum/index.php';
$modversion['submit_feature_name'] = 'Feature Submission';
$modversion['disclaimer']          = _MI_WFCHANNEL_CHANNELDISCLAIMER;

$modversion['help']        = 'page=help';
$modversion['license']     = 'GNU GPL 2.0 or later';
$modversion['license_url'] = 'www.gnu.org/licenses/gpl-2.0.html';
$modversion['official']    = 0;
$modversion['image']       = 'images/wfchannel_slogo.png';
$modversion['dirname']     = 'wfchannel';

$modversion['dirname'] = basename(__DIR__);

$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16']        = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32']        = 'Frameworks/moduleclasses/icons/32';
//about
$modversion['release_date']        = '2015/06/29';
$modversion['module_website_url']  = 'www.xoops.org';
$modversion['module_website_name'] = 'XOOPS';
$modversion['module_status']       = 'Beta 1';
$modversion['min_php']             = '5.3.7';
$modversion['min_xoops']           = '2.5.7';
$modversion['min_admin']           = '1.1';
$modversion['min_db']              = array(
    'mysql'  => '5.0.7',
    'mysqli' => '5.0.7');

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/wfchannel.sql';
// Tables created by sql file (without prefix!)
$modversion['tables'][] = 'wfcpages';
$modversion['tables'][] = 'wfclink';
$modversion['tables'][] = 'wfcrefer';
$modversion['tables'][] = 'wfcrefers';
// Admin things
$modversion['hasAdmin']    = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex']  = 'admin/index.php';
$modversion['adminmenu']   = 'admin/menu.php';
// Additionnal script executed during install update
$modversion['onInstall']   = 'include/oninstall.php';
$modversion['onUpdate']    = 'include/onupdate.php';
$modversion['onUninstall'] = 'include/onuninstall.php';
// Blocks
// Menu
$modversion['hasMain'] = 1;
// Search
$modversion['hasSearch']      = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'wfchannel_search';
// Comments
$modversion['hasComments']          = 1;
$modversion['comments']['pageName'] = 'index.php';
$modversion['comments']['itemName'] = 'cid';
// Comment callback functions
$modversion['comments']['callbackFile']        = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'wfchannel_com_approve';
$modversion['comments']['callback']['update']  = 'wfchannel_com_update';

//help files
$i                                     = 0;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_OVERVIEW;
$modversion['helpsection'][$i]['link'] = 'page=help';
++$i;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_REQUIREMENTS;
$modversion['helpsection'][$i]['link'] = 'page=__requirements';
++$i;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_INSTALL;
$modversion['helpsection'][$i]['link'] = 'page=__install';
++$i;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_UPDATE;
$modversion['helpsection'][$i]['link'] = 'page=__update';
++$i;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_HOWTO;
$modversion['helpsection'][$i]['link'] = 'page=__howto';
++$i;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_CREDITS;
$modversion['helpsection'][$i]['link'] = 'page=__credits';
++$i;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_DESCLAIMER;
$modversion['helpsection'][$i]['link'] = 'page=__disclaimer';
++$i;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_LICENSE;
$modversion['helpsection'][$i]['link'] = 'page=__license';
++$i;
$modversion['helpsection'][$i]['name'] = _MI_WFCHANNEL_SUPPORT;
$modversion['helpsection'][$i]['link'] = 'page=__support';



//define('_MI_WFCHANNEL_REQUIREMENTS', 'Requirements');
////define('_MI_WFCHANNEL_INSTALL', 'Install');
//define('_MI_WFCHANNEL_UPDATE', 'Update');
//define('_MI_WFCHANNEL_HOWTO', 'HowTo');
//define('_MI_WFCHANNEL_HISTORY', 'History');
//define('_MI_WFCHANNEL_CREDITS', 'Credits');
//define('_MI_WFCHANNEL_DESCLAIMER', 'Disclaimer');
//define('_MI_WFCHANNEL_LICENSE', 'License');
//define('_MI_WFCHANNEL_SUPPORT', 'Support');


/**
 * Notifications
 */
$modversion['hasNotification']             = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'wfchannel_notify_iteminfo';

$modversion['notification']['category'][] = array(
    'name'           => 'global',
    'title'          => _MI_WFCHANNEL_GLOBALNOTIFYCAT_TITLE,
    'description'    => '_MI_WFCHANNEL_GLOBALNOTIFYCAT_DESC',
    'subscribe_from' => array('index.php'),
    'item_name'      => '');

$modversion['notification']['category'][] = array(
    'name'           => 'page',
    'title'          => _MI_WFCHANNEL_PAGENOTIFYCAT_TITLE,
    'description'    => '_MI_WFCHANNEL_PAGENOTIFYCAT_DESC',
    'subscribe_from' => array('index.php'),
    'allow_bookmark' => 1,
    'item_name'      => 'cid');

$modversion['notification']['event'][] = array(
    'name'          => 'page_modified',
    'category'      => 'global',
    'title'         => _MI_WFCHANNEL_GLOBALNOTIFY_TITLE,
    'caption'       => _MI_WFCHANNEL_GLOBALNOTIFY_CAPTION,
    'description'   => '_MI_WFCHANNEL_GLOBALNOTIFY_DESC',
    'mail_template' => 'global_pagemodified_notify',
    'mail_subject'  => '_MI_WFCHANNEL_GLOBALNOTIFY_SUBJECT');

$modversion['notification']['event'][] = array(
    'name'          => 'page_new',
    'category'      => 'global',
    'title'         => _MI_WFCHANNEL_GLOBALNEWNOTIFY_TITLE,
    'caption'       => _MI_WFCHANNEL_GLOBALNEWNOTIFY_CAPTION,
    'description'   => '_MI_WFCHANNEL_GLOBALNEWNOTIFY_DESC',
    'mail_template' => 'global_pagenew_notify',
    'mail_subject'  => '_MI_WFCHANNEL_GLOBALNEWNOTIFY_SUBJECT');

$modversion['notification']['event'][] = array(
    'name'          => 'page_modified',
    'category'      => 'page',
    'title'         => _MI_WFCHANNEL_PAGENOTIFY_TITLE,
    'caption'       => _MI_WFCHANNEL_PAGENOTIFY_CAPTION,
    'description'   => '_MI_WFCHANNEL_PAGENOTIFY_DESC',
    'mail_template' => 'global_pagemodified_notify',
    'mail_subject'  => '_MI_WFCHANNEL_PAGENOTIFY_SUBJECT');

$modversion['notification']['event'][] = array(
    'name'          => 'page_new',
    'category'      => 'page',
    'title'         => _MI_WFCHANNEL_PAGENEWNOTIFY_TITLE,
    'caption'       => _MI_WFCHANNEL_PAGENEWNOTIFY_CAPTION,
    'description'   => '_MI_WFCHANNEL_PAGENEWNOTIFY_DESC',
    'mail_template' => 'global_pagenew_notify',
    'mail_subject'  => '_MI_WFCHANNEL_PAGENEWNOTIFY_SUBJECT');

/**
 * Blocks
 */
$modversion['blocks'][1]['file']        = 'wfc_block.new.php';
$modversion['blocks'][1]['name']        = _MI_WFCHANNEL_BNAME1;
$modversion['blocks'][1]['description'] = 'Shows recently added donwload files';
$modversion['blocks'][1]['show_func']   = 'b_wfc_new_show';
$modversion['blocks'][1]['edit_func']   = 'b_wfc_new_edit';
$modversion['blocks'][1]['options']     = 'published|10|19|M/d/Y|' . $modversion['dirname'];
$modversion['blocks'][1]['template']    = 'wfchannel_block_new.html';

$modversion['blocks'][2]['file']        = 'wfc_block.menu.php';
$modversion['blocks'][2]['name']        = _MI_WFCHANNEL_BNAME2;
$modversion['blocks'][2]['description'] = 'Shows Main menu type block';
$modversion['blocks'][2]['show_func']   = 'b_wfc_menu_show';
$modversion['blocks'][2]['edit_func']   = 'b_wfc_menu_edit';
$modversion['blocks'][2]['options']     = 'weight|10|19|' . $modversion['dirname'];
$modversion['blocks'][2]['template']    = 'wfchannel_block_menu.html';
// Templates
$modversion['templates'][1]['file']        = 'wfchannel_index.html';
$modversion['templates'][1]['description'] = 'Display index.';
$modversion['templates'][2]['file']        = 'wfchannel_linktous.html';
$modversion['templates'][2]['description'] = 'Display Link to Us page.';
$modversion['templates'][3]['file']        = 'wfchannel_refer.html';
$modversion['templates'][3]['description'] = 'Display refer page.';
$modversion['templates'][4]['file']        = 'wfchannel_banned.html';
$modversion['templates'][4]['description'] = 'Display a banned page.';
$modversion['templates'][5]['file']        = 'wfchannel_channellinks.html';
$modversion['templates'][5]['description'] = 'Display channel links within pages.';
$modversion['templates'][6]['file']        = 'wfchannel_emailerror.html';
$modversion['templates'][6]['description'] = 'Display channel email error page.';

$modversion['config'][] = array(
    'name'        => 'htmluploaddir',
    'title'       => '_MI_WFCHANNEL_HTMLUPLOADDIR',
    'description' => '_MI_WFCHANNEL_HTMLUPLOADDIRDSC',
    'formtype'    => 'textbox',
    'valuetype'   => 'text',
    'default'     => 'modules/' . $modversion['dirname'] . '/html');

$modversion['config'][] = array(
    'name'        => 'uploaddir',
    'title'       => '_MI_WFCHANNEL_UPLOADDIR',
    'description' => '_MI_WFCHANNEL_UPLOADDIRDSC',
    'formtype'    => 'textbox',
    'valuetype'   => 'text',
    'default'     => 'modules/' . $modversion['dirname'] . '/images');

$modversion['config'][] = array(
    'name'        => 'linkimages',
    'title'       => '_MI_WFCHANNEL_LINKIMAGES',
    'description' => '_MI_WFCHANNEL_UPLOADDIRDSC',
    'formtype'    => 'textbox',
    'valuetype'   => 'text',
    'default'     => 'modules/' . $modversion['dirname'] . '/images/linkimages');

$modversion['config'][] = array(
    'name'        => 'maxfilesize',
    'title'       => '_MI_WFCHANNEL_MAXFILESIZE',
    'description' => '_MI_WFCHANNEL_MAXFILESIZEDSC',
    'formtype'    => 'textbox',
    'valuetype'   => 'int',
    'default'     => 120000);

$modversion['config'][] = array(
    'name'        => 'maximgwidth',
    'title'       => '_MI_WFCHANNEL_IMGWIDTH',
    'description' => '_MI_WFCHANNEL_IMGWIDTHDSC',
    'formtype'    => 'textbox',
    'valuetype'   => 'int',
    'default'     => 600);

$modversion['config'][] = array(
    'name'        => 'maximgheight',
    'title'       => '_MI_WFCHANNEL_IMGHEIGHT',
    'description' => '_MI_WFCHANNEL_IMGHEIGHTDSC',
    'formtype'    => 'textbox',
    'valuetype'   => 'int',
    'default'     => 600);

$modversion['config'][] = array(
    'name'        => 'perpage',
    'title'       => '_MI_WFCHANNEL_PERPAGE',
    'description' => '_MI_MYDOWNLOADS_PERPAGEDSC',
    'formtype'    => 'select',
    'valuetype'   => 'int',
    'default'     => 10,
    'options'     => array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50));

$modversion['config'][] = array(
    'name'        => 'displaypagetitle',
    'title'       => '_MI_WFCHANNEL_DISPLAYTITLE',
    'description' => '_MI_WFCHANNEL_DISPLAYTITLEDSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => 1);

$modversion['config'][] = array(
    'name'        => 'use_wysiwyg',
    'title'       => '_MI_WFCHANNEL_WYSIWYG',
    'description' => '_MI_WFCHANNEL_WYSIWYGDSC',
    'formtype'    => 'select',
    'valuetype'   => 'text',
    'default'     => 'dhtmltextarea',
    'options'     => array('Plain Editor' => 'textarea', 'Xoops Editor' => 'dhtmltextarea', 'Tiny Editor' => 'tinymce', 'FCK Editor' => 'ckeditor'));

$modversion['config'][] = array(
    'name'        => 'banned',
    'title'       => '_MI_WFCHANNEL_BANNED',
    'description' => '_MI_WFCHANNEL_BANNEDDSC',
    'formtype'    => 'textarea',
    'valuetype'   => 'text',
    'default'     => '');

$modversion['config'][] = array(
    'name'        => 'displaybookmarks',
    'title'       => '_MI_WFCHANNEL_BOOKMARK',
    'description' => '_MI_WFCHANNEL_BOOKMARKDSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => '1');

$modversion['config'][] = array(
    'name'        => 'allowaddthiscode',
    'title'       => '_MI_WFCHANNEL_ALLOWADDTHISCODE',
    'description' => '_MI_WFCHANNEL_ALLOWADDTHISCODE_DSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => '0');

$modversion['config'][] = array(
    'name'        => 'addthiscode',
    'title'       => '_MI_WFCHANNEL_ADDTHISCODE',
    'description' => '_MI_WFCHANNEL_ADDTHISCODE_DSC',
    'formtype'    => 'textarea',
    'valuetype'   => 'text',
    'default'     => '');

$modversion['config'][] = array(
    'name'        => 'bookmarktextadd',
    'title'       => '_MI_WFCHANNEL_ALLOWBMTEXT',
    'description' => '_MI_WFCHANNEL_ALLOWBMTEXT_DSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => '0');

$modversion['config'][] = array(
    'name'        => 'bookmarklayout',
    'title'       => '_MI_WFCHANNEL_BMLAYOUT',
    'description' => '_MI_WFCHANNEL_BMLAYOUT_DSC',
    'formtype'    => 'select',
    'valuetype'   => 'int',
    'default'     => '0',
    'options'     => array(
        _MI_WFCHANNEL_HORIZONTAL => 0,
        _MI_WFCHANNEL_VERTICAL   => 1));

$modversion['config'][] = array(
    'name'        => 'menulinks',
    'title'       => '_MI_WFCHANNEL_MENULINKS',
    'description' => '_MI_WFCHANNEL_MENULINKSDSC',
    'formtype'    => 'select',
    'valuetype'   => 'int',
    'default'     => 3,
    'options'     => array('None' => 0, 'Both' => 1, 'Top' => 2, 'Bottom' => 3));

$modversion['config'][] = array(
    'name'        => 'pageicon',
    'title'       => '_MI_WFCHANNEL_DISPLAYICONS',
    'description' => '_MI_WFCHANNEL_DISPLAYICONS_DSC',
    'formtype'    => 'select_multi',
    'valuetype'   => 'array',
    'default'     => array(1, 2, 3, 4, 5),
    'options'     => array('_MI_WFCHANNEL_NONE' => 0, '_MI_WFCHANNEL_RSS_ICON' => 1, '_MI_WFCHANNEL_PRINT_ICON' => 2, '_MI_WFCHANNEL_PDF_ICON' => 3, '_MI_WFCHANNEL_EMAILICON_ICON' => 4, '_MI_WFCHANNEL_BOOKMARK_ICON' => 5));

$modversion['config'][] = array(
    'name'        => 'act_refer',
    'title'       => '_MI_WFCHANNEL_ACTIVATEREFERS',
    'description' => '_MI_WFCHANNEL_ACTIVATEREFERS_DSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => '1');

$modversion['config'][] = array(
    'name'        => 'act_link',
    'title'       => '_MI_WFCHANNEL_ACTIVATELINKS',
    'description' => '_MI_WFCHANNEL_ACTIVATELINKS_DSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => '1');

$modversion['config'][] = array(
    'name'        => 'allow_admin',
    'title'       => '_MI_WFCHANNEL_ALLOWADMIN',
    'description' => '_MI_WFCHANNEL_ALLOWADMIN_DSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => '0');

$modversion['config'][] = array(
    'name'        => 'xoopstags',
    'title'       => '_MI_WFCHANNEL_XOOPSTAGS',
    'description' => '_MI_WFCHANNEL_XOOPSTAGS_DSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => '0');

$modversion['config'][] = array(
    'name'        => 'copyrighttext',
    'title'       => '_MI_WFCHANNEL_COPYRIGHT',
    'description' => '_MI_WFCHANNEL_COPYRIGHT_DSC',
    'formtype'    => 'textbox',
    'valuetype'   => 'text',
    'default'     => 'Copyright © %s %s');

$modversion['config'][] = array(
    'name'        => 'allow_pnlinks',
    'title'       => '_MI_WFCHANNEL_PNKINKS',
    'description' => '_MI_WFCHANNEL_PNKINKS_DSC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => '0');
